name: KimoTools
version: 0.0.1337
main: me.mrkimo.kimotools.kimotools
author: MrKimo
website: None
commands:
     gethealth:
          description: getHealth of a yourself or others
          usage: /<command> [Player]
          permission: kimotools.gethealth
     serverteam:
          description: display serverteam
          usage: /serverteam
     aflame:
          description: set a player aflame
          usage: /<command> [Player]
          permission: kimotools.aflame
     tp:
          description: teleport
          usage: /<command> <Player> [Player]
          permission: kimotools.tp
          permission: kimotools.tp.others
     tphere:
          description: teleport here
          usage: /<command> <Player>
          permission: kimotools.tp.here
     s:
          description: teleport here
          usage: /<command> <Player>
          permission: kimotools.tp.here
     warp:
          description: warp
          usage: /<command> <warp>
          permission: kimotools.warp
     setwarp:
          description: setwarp
          usage: /<command> <warpname>
          permission: kimotools.warp.mod
     delwarp:
          description: delwarp
          usage: /<command> <warpname>
          permission: kimotools.warp.mod
     warps:
          description: list warps
          usage: /<command>
          permission: kimotools.warp
     home:
          description: home
          usage: /<command> <home>
          permission: kimotools.home
     sethome:
          description: sethome
          usage: /<command> <homename>
          permission: kimotools.home
     delhome:
          description: delhome
          usage: /<command> <homename>
          permission: kimotools.home
     homes:
          description: list homes
          usage: /<command>
          permission: kimotools.home
     i:
          description: various item commands
          usage: /<command> args args args ...
          permission: kimotools.item.give
          permission: kimotools.item.clone
          permission: kimotools.item.enchant
     item:
          description: various item commands
          usage: /<command> args args args ...
          permission: kimotools.item.give
          permission: kimotools.item.clone
          permission: kimotools.item.enchant
permissions:
  kimotools.gethealth:
    description: gethealth command
  kimotools.aflame:
    description: aflame command
  kimotools.tp:
    description: beam command
  kimotools.tp.others:
    description: beam others command
  kimotools.tp.here:
    description: beam2me command
  kimotools.warp:
    description: warp / warplist command
  kimotools.warp.mod:
    description: modify warps
  kimotools.home:
    description: home commands
  kimotools.item.give:
    description: item give command
  kimotools.item.clone:
    description: item clone command
  kimotools.item.enchant:
    description: item enchant command
