name: KimoTools
version: 0.0.1337
main: me.mrkimo.kimotools.kimotools
author: MrKimo
website: None
commands:
     gethealth:
          description: getHealth of a yourself or others
          usage: /<command> [Player]
          permission: kimotools.gethealth
     serverteam:
          description: display serverteam
          usage: /serverteam
     aflame:
          description: set a player aflame
          usage: /<command> [Player]
          permission: kimotools.aflame
     beam:
          description: teleport
          usage: /<command> <Player> [Player]
          permission: kimotools.beam
          permission: kimotools.beam.others
permissions:
  kimotools.gethealth:
    description: gethealth command
  kimotools.aflame:
    description: aflame command
  kimotools.beam:
    description: beam command
  kimotools.beam.others:
    description: beam others command
